name: dart_azure_cosmosdb
description: A starting point for Dart libraries or applications.
version: 0.9.0
repository: https://github.com/Pat992/dart_azure_cosmosdb
homepage: https://github.com/Pat992/dart_azure_cosmosdb

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mockito: ^5.3.2
  build_runner: ^2.3.3

dependencies:
  crypto: ^3.0.2
  http: ^0.13.5
